### ISSUE TITLE
Incorrect memory to disk space ratio

### ISSUE THREAD

**Issue by rwd** [IBM-Bluemix-Docs/ComposeForPostgreSQL#1]
The [architecture document](https://github.com/IBM-Bluemix-Docs/ComposeForPostgreSQL/blob/master/reference-architecture.md#auto-scaling) states:
> Memory is based on a ratio of provisioned disk space at 1:4.

The ratio is in fact 1:10, as stated at https://console.bluemix.net/docs/services/ComposeForPostgreSQL/pricing.html#pricing

**Comment by DailyAlice** [comment]
Thank you. I do believe this is now fixed.
